name: Build and push Docker images

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: .devops/full.Dockerfile
            tag: full
          - dockerfile: .devops/full-cuda.Dockerfile
            tag: full-cuda
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.tag }}
          cache-from: type=gha,scope=${{ matrix.tag }}
          cache-to: type=gha,scope=${{ matrix.tag }},mode=max

  build:
    runs-on: ubuntu-latest
    needs: build-base
    strategy:
      matrix:
        include:
          - dockerfile: .devops/llama-cli.Dockerfile
            tag: llama-cli
            build-args: ""
          - dockerfile: .devops/llama-cli-cuda.Dockerfile
            tag: llama-cli-cuda
            build-args: |
              FULL_CUDA_IMAGE=ghcr.io/volkermauel/ik_llama.cpp:full-cuda
          - dockerfile: .devops/llama-server.Dockerfile
            tag: llama-server
            build-args: |
              FULL_CUDA_IMAGE=ghcr.io/volkermauel/ik_llama.cpp:full-cuda
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.tag }}
          cache-from: type=gha,scope=${{ matrix.tag }}
          cache-to: type=gha,scope=${{ matrix.tag }},mode=max
          build-args: ${{ matrix.build-args }}
